sudo: required
dist: trusty

language: cpp

addons:
  apt:
    packages:
      - g++-5
    sources:
      - ubuntu-toolchain-r-test

before-install:
    - sudo apt-get update

install:
    - apt-get install libboost-dev
    - apt-get install doxygen
    - apt-get install libgtest-dev
    - apt-get install valgrind
    - ls -al /usr/src
    - cd /usr/src/gtest
    - cmake CMakeLists.txt
    - make
    - cp *.a /usr/lib
    - cd -

before_script:
    - uname -a
    - printenv | sort
    - apt list --installed
    - make versions

script:
    - date
    - ls -al
    - make test
